### PR TITLE
Optimized assets + added contact info to the fabric.mod.json file.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Lossless compression (oxipng).

### CODE REVIEW

**Comment by Keksuccino** [comment]
What is this and why? :D

**Comment by RDKRACZ** [comment]
> What is this and why? :D

Just for a little smaller jar size. I can send the changed files in a zip archive if you prefer to commit by yourself (or just download them from my fork).
The tool - https://github.com/shssoichiro/oxipng

**Comment by Keksuccino** [comment]
Dude no offense, but don't you think you should let me choose what Gradle version, settings and setup I use?

**Comment by Keksuccino** [comment]
Thank you for your work, but will close this for now.
Images will be implemented in a future build eventually. Thanks.

**Pull request closed without merging**
